name: job_finder_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  go_router: ^13.2.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  cupertino_icons: ^1.0.2
  blur: 3.1.0
  http_parser: ^4.0.2
  mime: ^1.0.5
  path: 1.8.3
  image_picker: 1.0.8
  flutter_spinkit: ^5.2.1
  quickalert: ^1.1.0
  flutter_dotenv: ^5.1.0
  dotted_border: ^2.1.0
  file_picker: ^5.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
