name: job_finder_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  provider: ^6.0.5
  go_router: ^14.2.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  cupertino_icons: ^1.0.2
  blur: ^4.0.0
  http_parser: ^4.0.2
  mime: ^1.0.5
  path: ^1.9.0
  image_picker: ^1.1.2
  flutter_spinkit: ^5.2.1
  quickalert: ^1.1.0
  flutter_dotenv: ^5.1.0
  dotted_border: ^2.1.0
  file_picker: ^8.0.5
  intl: ^0.19.0
  date_picker_plus: ^4.0.0
  expandable_page_view: ^1.0.17
  shadow_overlay: ^1.0.5
  photo_view: ^0.15.0
  flutter_quill: ^10.8.2
  url_launcher: ^6.3.0
  # device_info_plus: ^10.1.0
  # flutter_keyboard_visibility: ^6.0.0
  # flutter_quill_extensions: ^10.8.2
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  # flutter_file_downloader: ^2.0.0
  awesome_notifications_core: ^0.9.3
  awesome_notifications: ^0.9.3+1
  open_file_manager: ^1.0.2
  socket_io_client: ^3.0.0
  connectivity_plus: ^6.0.5
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  responsive_builder: ^0.7.1
  toastification: ^2.3.0
  number_pagination: ^1.1.5
  universal_html: ^2.2.4

dependency_overrides:
  flutter_plugin_android_lifecycle: 2.0.23

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
