List<Map<String, String>> jobseekers = [
  {
    'firstName': 'Văn Hưng',
    'lastName': 'Nguyễn',
    'email': 'hungnguyen@example.com',
    'province': 'Hà Nội',
    'phone': '+84 913456789',
  },
  {
    'firstName': 'Thị Mai',
    'lastName': 'Trần',
    'email': 'maitran@example.com',
    'province': 'Hồ Chí Minh',
    'phone': '+84 916234567',
  },
  {
    'firstName': 'Đức Anh',
    'lastName': 'Lê',
    'email': 'anhle@example.com',
    'province': 'Đà Nẵng',
    'phone': '+84 912987654',
  },
  {
    'firstName': 'Thị Hương',
    'lastName': 'Phạm',
    'email': 'huongpham@example.com',
    'province': 'Hải Phòng',
    'phone': '+84 938765432',
  },
  {
    'firstName': 'Văn Nam',
    'lastName': 'Hoàng',
    'email': 'namhoang@example.com',
    'province': 'Bình Dương',
    'phone': '+84 934567890',
  },
  {
    'firstName': 'Thị Lan',
    'lastName': 'Đỗ',
    'email': 'landdo@example.com',
    'province': 'Đồng Nai',
    'phone': '+84 916345678',
  },
  {
    'firstName': 'Minh Đức',
    'lastName': 'Nguyễn',
    'email': 'minhduc@example.com',
    'province': 'Cần Thơ',
    'phone': '+84 919876543',
  },
  {
    'firstName': 'Thị Ngọc',
    'lastName': 'Võ',
    'email': 'ngocvo@example.com',
    'province': 'Quảng Ninh',
    'phone': '+84 915234567',
  },
  {
    'firstName': 'Văn Hải',
    'lastName': 'Phan',
    'email': 'haiphan@example.com',
    'province': 'Nghệ An',
    'phone': '+84 933456789',
  },
  {
    'firstName': 'Thị Thảo',
    'lastName': 'Lý',
    'email': 'thaly@example.com',
    'province': 'Thừa Thiên Huế',
    'phone': '+84 914987654',
  },
  {
    'firstName': 'Thị Hạnh',
    'lastName': 'Nguyễn',
    'email': 'hanhnguyen@example.com',
    'province': 'Bình Thuận',
    'phone': '+84 917234567',
  },
  {
    'firstName': 'Văn Hùng',
    'lastName': 'Lê',
    'email': 'hungvanle@example.com',
    'province': 'Khánh Hòa',
    'phone': '+84 918765432',
  },
  {
    'firstName': 'Thị Minh',
    'lastName': 'Vũ',
    'email': 'minhvu@example.com',
    'province': 'Long An',
    'phone': '+84 934987654',
  },
  {
    'firstName': 'Văn Sơn',
    'lastName': 'Trịnh',
    'email': 'sonttrinh@example.com',
    'province': 'Quảng Nam',
    'phone': '+84 919234567',
  },
  {
    'firstName': 'Thị Mai',
    'lastName': 'Bùi',
    'email': 'maibui@example.com',
    'province': 'Bà Rịa - Vũng Tàu',
    'phone': '+84 932345678',
  },
  {
    'firstName': 'Văn Khoa',
    'lastName': 'Đặng',
    'email': 'khoa@dang.com',
    'province': 'Bình Phước',
    'phone': '+84 917876543',
  },
  {
    'firstName': 'Thị Liên',
    'lastName': 'Lương',
    'email': 'lienluong@example.com',
    'province': 'Tây Ninh',
    'phone': '+84 935234567',
  },
  {
    'firstName': 'Văn Tùng',
    'lastName': 'Trương',
    'email': 'tungtruong@example.com',
    'province': 'Ninh Bình',
    'phone': '+84 918345678',
  },
  {
    'firstName': 'Thị Hoa',
    'lastName': 'Nguyễn',
    'email': 'hoanguyen@example.com',
    'province': 'Quảng Trị',
    'phone': '+84 933876543',
  },
  {
    'firstName': 'Văn Dũng',
    'lastName': 'Phạm',
    'email': 'dungpham@example.com',
    'province': 'Kiên Giang',
    'phone': '+84 934123456',
  },
];
