// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe-huXrDGK_yqmfHLQEL90TC3ekK4L8zo',
    appId: '1:2673235234:web:48bce4e19be25ada7f817b',
    messagingSenderId: '2673235234',
    projectId: 'jobfinderapp-b314a',
    authDomain: 'jobfinderapp-b314a.firebaseapp.com',
    storageBucket: 'jobfinderapp-b314a.appspot.com',
    measurementId: 'G-XQH9RKV9SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaQ1lSltrJCe-1SEx_h1v2TTfl31xUBCU',
    appId: '1:2673235234:android:eb5065181c172ebd7f817b',
    messagingSenderId: '2673235234',
    projectId: 'jobfinderapp-b314a',
    storageBucket: 'jobfinderapp-b314a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvW1cT4tsOxh9XWjR8M84W041IBRfS84s',
    appId: '1:2673235234:ios:da8cbd09405959967f817b',
    messagingSenderId: '2673235234',
    projectId: 'jobfinderapp-b314a',
    storageBucket: 'jobfinderapp-b314a.appspot.com',
    iosBundleId: 'com.example.jobFinderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvW1cT4tsOxh9XWjR8M84W041IBRfS84s',
    appId: '1:2673235234:ios:da8cbd09405959967f817b',
    messagingSenderId: '2673235234',
    projectId: 'jobfinderapp-b314a',
    storageBucket: 'jobfinderapp-b314a.appspot.com',
    iosBundleId: 'com.example.jobFinderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe-huXrDGK_yqmfHLQEL90TC3ekK4L8zo',
    appId: '1:2673235234:web:eb1d0162235ae9697f817b',
    messagingSenderId: '2673235234',
    projectId: 'jobfinderapp-b314a',
    authDomain: 'jobfinderapp-b314a.firebaseapp.com',
    storageBucket: 'jobfinderapp-b314a.appspot.com',
    measurementId: 'G-ZPYVHNG2RZ',
  );
}