List<String> getJobseekerSkillHint() {
  return [
    "Giao tiếp hiệu quả",
    "Giải quyết vấn đề",
    "Làm việc nhóm",
    "Quản lý thời gian",
    "Thích nghi",
    "Tư duy phản biện",
    "Quản lý dự án",
    "Tự học và phát triển",
    "Chủ động",
    "Tư duy sáng tạo",
    "Quản lý căng thẳng",
    "Đạo đức nghề nghiệp",
    "Kỹ năng lắng nghe",
    "Kỹ năng thuyết trình",
    "Kỹ năng giao tiếp qua email",
    "Kỹ năng đàm phán",
    "Khả năng phân tích",
    "Lãnh đạo",
    "Kỹ năng viết báo cáo",
    "Kỹ năng tổ chức",
    "Lập trình hướng đối tượng (OOP)",
    "Lập trình hàm (Functional Programming)",
    "Lập trình thủ tục (Procedural Programming)",
    "Lập trình song song (Parallel Programming)",
    "Lập trình bất đồng bộ (Asynchronous Programming)",
    "Lập trình hướng sự kiện (Event-driven Programming)",
    "Lập trình phản ứng (Reactive Programming)",
    "Lập trình logic",
    "Thiết kế và phân tích thuật toán",
    "Kỹ thuật giải quyết vấn đề",
    "Quản lý bộ nhớ",
    "Quản lý ngoại lệ (Exception Handling)",
    "Thiết kế cơ sở dữ liệu",
    "Tối ưu hóa mã nguồn",
    "Phát triển web phía client (Frontend Development)",
    "Phát triển web phía server (Backend Development)",
    "Phát triển ứng dụng di động",
    "Phát triển game",
    "Viết và sử dụng API",
    "Tích hợp hệ thống",
    "Viết unit test",
    "Phân tích yêu cầu phần mềm",
    "Quản lý phiên bản (Version Control)",
    "Quản lý cấu hình phần mềm",
    "Kỹ năng DevOps",
    "Lập trình nhúng",
    "Lập trình hệ thống",
    "Phát triển phần mềm mã nguồn mở",
    "Kỹ năng bảo mật lập trình",
    "Lập trình đa nền tảng",
    "Phát triển phần mềm Agile/Scrum",
    "Kỹ năng debug",
    "Kỹ năng refactor mã nguồn",
    "Sử dụng các công cụ CI/CD",
    "Viết tài liệu kỹ thuật",
    "Lập trình máy học",
    "Lập trình trí tuệ nhân tạo",
    "Lập trình xử lý dữ liệu lớn (Big Data)",
    "Phát triển phần mềm dựa trên mô hình (Model-driven Development)",
    "Phát triển phần mềm dựa trên kiểm thử (Test-driven Development)",
    "Python",
    "JavaScript",
    "Java",
    "C++",
    "C#",
    "Ruby",
    "PHP",
    "Swift",
    "Kotlin",
    "Go",
    "Rust",
    "TypeScript",
    "SQL",
    "HTML",
    "CSS",
    "R",
    "MATLAB",
    "Perl",
    "Objective-C",
    "Scala",
    "Shell scripting (Bash)",
    "Dart",
    "Haskell",
    "Lua",
    "Elixir",
    "Clojure",
    "Groovy",
    "Erlang",
    "VB.NET",
    "Assembly language",
    "Fortran",
    "COBOL",
    "F#",
    "Ada",
    "Prolog",
    "Lisp",
    "Scheme",
    "VHDL",
    "Verilog",
    "PL/SQL",
    "Tcl",
    "Julia",
    "SAS",
    "ABAP",
    "LabVIEW",
    "Golang",
    "Solidity"
  ];
}

List<String> getDegree() {
  return [
    "Trung học",
    "Trung cấp",
    "Bằng liên kết",
    "Cao đẳng",
    "Cử nhân",
    "Thạc sĩ",
    "Tiến sĩ",
    "Khác"
  ];
}

List<String> getTechnologyList = [
  // Ngôn ngữ lập trình
  "JavaScript",
  "Python",
  "Java",
  "C#",
  "C++",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "TypeScript",
  "Go",
  "Rust",
  "Scala",
  "Perl",
  "R",
  "Dart",
  "Haskell",
  "Lua",
  "MATLAB",
  "Objective-C",

  // Công nghệ web
  "HTML",
  "CSS",
  "React",
  "Angular",
  "Vue.js",
  "Svelte",
  "Node.js",
  "Django",
  "Flask",
  "Ruby on Rails",
  "ASP.NET",
  "Spring",
  "Express.js",
  "Next.js",
  "Nuxt.js",
  "Gatsby",
  "Ember.js",
  "Backbone.js",
  "Bootstrap",
  "Tailwind CSS",

  // Cơ sở dữ liệu
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "SQLite",
  "Oracle Database",
  "Microsoft SQL Server",
  "Firebase",
  "Redis",
  "Cassandra",
  "Elasticsearch",
  "MariaDB",
  "CouchDB",
  "DynamoDB",
  "Neo4j",
  "InfluxDB",

  // Công nghệ DevOps
  "Docker",
  "Kubernetes",
  "Jenkins",
  "Travis CI",
  "CircleCI",
  "GitLab CI/CD",
  "Ansible",
  "Puppet",
  "Chef",
  "Terraform",
  "Vagrant",
  "Nagios",
  "Prometheus",
  "Grafana",

  // Dịch vụ đám mây
  "Amazon Web Services (AWS)",
  "Microsoft Azure",
  "Google Cloud Platform (GCP)",
  "IBM Cloud",
  "Oracle Cloud",
  "Heroku",
  "DigitalOcean",
  "Linode",
  "Vultr",
  "Cloudflare",

  // Công nghệ di động
  "React Native",
  "Flutter",
  "Xamarin",
  "Ionic",
  "Apache Cordova",

  // Công nghệ AI/ML
  "TensorFlow",
  "Keras",
  "PyTorch",
  "Scikit-learn",
  "OpenCV",
  "Pandas",
  "NumPy",
  "SciPy",
  "NLTK",
  "spaCy",
  "Hugging Face Transformers",
  "RapidMiner",

  // Các công nghệ khác
  "Blockchain",
  "Ethereum",
  "Hyperledger",
  "Solidity",
  "GraphQL",
  "RESTful API",
  "gRPC",
  "WebAssembly",
  "Microservices",
  "Serverless",
  "Progressive Web Apps (PWA)",
  "Internet of Things (IoT)",
  "Virtual Reality (VR)",
  "Augmented Reality (AR)"
];
